# Generated by Django 2.2.7 on 2019-12-13 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favouriting_users',
            field=models.ManyToManyField(related_name='favourite_quotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
